"""Add more fields to Role

Revision ID: 1e0c21cbacb3
Revises: 9ffd826aea57
Create Date: 2026-07-18 13:35:42.294168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0c21cbacb3'
down_revision: Union[str, Sequence[str], None] = '9ffd826aea57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('template_version', sa.Integer(), nullable=False))
    op.add_column('roles', sa.Column('is_customized', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_customized')
    op.drop_column('roles', 'template_version')
    # ### end Alembic commands ###
