"""Remove church and role from User

Revision ID: 1f2deffc3a7e
Revises: d0a127905e6c
Create Date: 2026-04-02 18:28:31.338313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2deffc3a7e'
down_revision: Union[str, Sequence[str], None] = 'd0a127905e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_church_id_churches'), 'users', type_='foreignkey')
    op.drop_column('users', 'church_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('church_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_users_church_id_churches'), 'users', 'churches', ['church_id'], ['id'])
    # ### end Alembic commands ###
