"""add admin attributes to membership

Revision ID: 2f4ad06c0a52
Revises: 7e79d92f028f
Create Date: 2026-04-06 11:51:57.006356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4ad06c0a52'
down_revision: Union[str, Sequence[str], None] = '7e79d92f028f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('memberships', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_primary_key(op.f('pk_memberships'), 'memberships', ['id'])
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'is_active')
    op.drop_column('memberships', 'id')
    op.drop_constraint(op.f('pk_memberships'), 'memberships', type_='primary')
    # ### end Alembic commands ###
