"""make church not nullable in church contact

Revision ID: 3ca2dd0f6e78
Revises: ae52c3d63a9e
Create Date: 2026-04-23 01:04:05.159405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca2dd0f6e78'
down_revision: Union[str, Sequence[str], None] = 'ae52c3d63a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('church_contact', 'church_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('church_contact', 'church_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
