"""add user to invite

Revision ID: 4c7653ddf2b3
Revises: 04f63b5b0aae
Create Date: 2026-05-27 17:11:29.399070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7653ddf2b3'
down_revision: Union[str, Sequence[str], None] = '04f63b5b0aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_codes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_invite_codes_user_id_users'), 'invite_codes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invite_codes_user_id_users'), 'invite_codes', type_='foreignkey')
    op.drop_column('invite_codes', 'user_id')
    # ### end Alembic commands ###
