"""set one membership per church and no church for superadmin

Revision ID: 5638e3fa1d8e
Revises: 2f4ad06c0a52
Create Date: 2026-04-06 14:51:18.114292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5638e3fa1d8e'
down_revision: Union[str, Sequence[str], None] = '2f4ad06c0a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memberships', 'church_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_user_church', 'memberships', ['user_id', 'church_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_church', 'memberships', type_='unique')
    op.alter_column('memberships', 'church_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
