"""Add system role relationship to Role

Revision ID: 59b6c3744823
Revises: ba38edae2a45
Create Date: 2026-07-18 14:23:23.414696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b6c3744823'
down_revision: Union[str, Sequence[str], None] = 'ba38edae2a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('system_role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_roles_system_role_id_system_roles'), 'roles', 'system_roles', ['system_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_roles_system_role_id_system_roles'), 'roles', type_='foreignkey')
    op.drop_column('roles', 'system_role_id')
    # ### end Alembic commands ###
