"""add church id to announcement

Revision ID: 7a309ca2266e
Revises: cd7b9ae5062c
Create Date: 2026-04-27 15:24:11.564338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a309ca2266e'
down_revision: Union[str, Sequence[str], None] = 'cd7b9ae5062c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('church_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_announcements_church_id_churches'), 'announcements', 'churches', ['church_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_announcements_church_id_churches'), 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'church_id')
    # ### end Alembic commands ###
