"""add admin attributes to church

Revision ID: 7e79d92f028f
Revises: 3b57ab19b959
Create Date: 2026-04-06 11:14:34.400562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e79d92f028f'
down_revision: Union[str, Sequence[str], None] = '3b57ab19b959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('churches', sa.Column('code', sa.String(), nullable=False))
    op.add_column('churches', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_churches_code'), 'churches', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_churches_code'), table_name='churches')
    op.drop_column('churches', 'is_active')
    op.drop_column('churches', 'code')
    # ### end Alembic commands ###
