"""add last_name and modify other user fields

Revision ID: 94b14da7e189
Revises: 9c38589f9951
Create Date: 2026-09-28 21:46:28.843177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b14da7e189'
down_revision: Union[str, Sequence[str], None] = '9c38589f9951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('uq_users_email_ci', 'users', [sa.literal_column('lower(btrim(email))')], unique=True)
    op.create_unique_constraint(op.f('uq_users_telegram_id'), 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_telegram_id'), 'users', type_='unique')
    op.drop_index('uq_users_email_ci', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
