"""make some fields nullable in Role

Revision ID: 963e5ca05ca5
Revises: 8c9e89d4ece4
Create Date: 2026-07-23 22:36:10.042541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963e5ca05ca5'
down_revision: Union[str, Sequence[str], None] = '8c9e89d4ece4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'template_version',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'template_version',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
