"""add created_by to User

Revision ID: 9b9d0058f4ba
Revises: 94b14da7e189
Create Date: 2026-10-06 18:09:53.882830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9d0058f4ba'
down_revision: Union[str, Sequence[str], None] = '94b14da7e189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_users_created_by_id_users'), 'users', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_created_by_id_users'), 'users', type_='foreignkey')
    op.drop_column('users', 'created_by_id')
    # ### end Alembic commands ###
