"""Make telegram id optional in User

Revision ID: 9f3f84efd9ec
Revises: 5638e3fa1d8e
Create Date: 2026-04-06 20:36:13.931387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3f84efd9ec'
down_revision: Union[str, Sequence[str], None] = '5638e3fa1d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
