"""Add membership_roles many to many

Revision ID: 9ffd826aea57
Revises: 4c5f089a1e6a
Create Date: 2026-07-13 22:02:06.309803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffd826aea57'
down_revision: Union[str, Sequence[str], None] = '4c5f089a1e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_roles',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_roles_membership_id_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_membership_roles_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'role_id', name=op.f('pk_membership_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_roles')
    # ### end Alembic commands ###
