"""add church theme

Revision ID: ae52c3d63a9e
Revises: 82f56092e40f
Create Date: 2026-04-20 15:28:48.296852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae52c3d63a9e'
down_revision: Union[str, Sequence[str], None] = '82f56092e40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church_theme',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('church_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('verse', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], name=op.f('fk_church_theme_church_id_churches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_church_theme')),
    sa.UniqueConstraint('church_id', 'year', name='unique_church_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('church_theme')
    # ### end Alembic commands ###
