"""Create system role model

Revision ID: ba38edae2a45
Revises: 1e0c21cbacb3
Create Date: 2026-07-18 13:41:45.883647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba38edae2a45'
down_revision: Union[str, Sequence[str], None] = '1e0c21cbacb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_system_roles_name'))
    )
    op.create_table('system_role_permissions',
    sa.Column('system_role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_system_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_role_id'], ['system_roles.id'], name=op.f('fk_system_role_permissions_system_role_id_system_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_role_id', 'permission_id', name=op.f('pk_system_role_permissions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_role_permissions')
    op.drop_table('system_roles')
    # ### end Alembic commands ###
