"""membership add category and update role

Revision ID: c705d4258f75
Revises: 9f3f84efd9ec
Create Date: 2026-04-20 14:29:20.988358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c705d4258f75'
down_revision: Union[str, Sequence[str], None] = '9f3f84efd9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'category')
    # ### end Alembic commands ###
