"""Create all announcement tables

Revision ID: cd7b9ae5062c
Revises: 3ca2dd0f6e78
Create Date: 2026-04-25 16:32:16.302373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7b9ae5062c'
down_revision: Union[str, Sequence[str], None] = '3ca2dd0f6e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_audience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_audience')),
    sa.UniqueConstraint('name', name=op.f('uq_announcement_audience_name'))
    )
    op.create_table('announcement_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_status')),
    sa.UniqueConstraint('name', name=op.f('uq_announcement_status_name'))
    )
    op.create_table('announcement_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_announcement_tags_name'))
    )
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(expire_at IS NULL OR publish_at IS NULL OR expire_at > publish_at)', name=op.f('ck_announcements_check_expire_after_publish')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_announcements_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['announcement_status.id'], name=op.f('fk_announcements_status_id_announcement_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_table('announcement_audience_link',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('audience_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_announcement_audience_link_announcement_id_announcements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audience_id'], ['announcement_audience.id'], name=op.f('fk_announcement_audience_link_audience_id_announcement_audience'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_id', 'audience_id', name=op.f('pk_announcement_audience_link'))
    )
    op.create_table('announcement_tag_link',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_announcement_tag_link_announcement_id_announcements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['announcement_tags.id'], name=op.f('fk_announcement_tag_link_tag_id_announcement_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_id', 'tag_id', name=op.f('pk_announcement_tag_link'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement_tag_link')
    op.drop_table('announcement_audience_link')
    op.drop_table('announcements')
    op.drop_table('announcement_tags')
    op.drop_table('announcement_status')
    op.drop_table('announcement_audience')
    # ### end Alembic commands ###
