"""Add code field to permission model

Revision ID: df04781294ad
Revises: a26b95a3046e
Create Date: 2026-07-13 20:27:46.886501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df04781294ad'
down_revision: Union[str, Sequence[str], None] = 'a26b95a3046e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('code', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_column('permissions', 'code')
    # ### end Alembic commands ###
